### PR TITLE
make running the samples part of the test procedure

### PR DESCRIPTION
**Pull request by tynovsky**
I've added a test which runs all the example scripts from samples directory. I've made only minimal adjustments to them to make it work. Please let me know if I can improve anything.

BTW, this PR is part of CPAN Pull Request Challenge. :-)

### CODE REVIEW

**Comment by ruz** [comment]
Can't we just assume that tests are run from the root of the repo, so we don't need FindBin?

**Comment by ruz** [comment]
merged manually with a tiny change

**Comment by ruz** [comment]
thank you

**Comment by tynovsky** [comment]
Thanks for merge!

**Pull request closed without merging**
