### PR TITLE
Correction min/max and min_range for two axis

### PR DESCRIPTION
**Pull request by Frank071**
This proposed change was filed by 'patermanns' in bug #62665 but never made it to a pull request.

All kudos to patermanns!

### CODE REVIEW

**Comment by ruz** [comment]
Hi,

This pull request was not ignored. two_axes == 2 is not documented, so the request is not complete. I played around with this and couldn't find any problems with this mode and decided to get rid of special value. Code should just check if y2's min value is set and then disable two axes zero point adjustments.

Will you update the patch?

**Comment by Frank071** [comment]
The obvious issue is the use of 'attributes' min_range/min_range_1/min_range_2 where it should use y_min_range/y1_min_range/y2_min_range. This is solved in the patch, without it there is no adjustment of the axes. Now probably this was the reason for the original author to introduce the option to set two_axes to '2' to explicitly make use of the patch (and any other value to leave it as it was).
I can correct it by simply removing the parts where adjust_axes is involved, but I don't know if this correct in all circumstances.

**Comment by Frank071** [comment]
I created another pull request that only has those attribute changes in.

**Comment by ruz** [comment]
I decided to go with https://github.com/ruz/GDGraph/commit/1367697fdee4f2852b4d197cf83121e5fc90b1c7

**Pull request closed without merging**
